name: kdellipspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.0.0
  - scipy>=1.13.0
  - matplotlib
  - cartopy
  - pyproj
  - obspy
  - compilers
  - gcc
  - gfortran
  - make
  - meson
  - ninja
  - pymc>=5.10.0
  - arviz>=0.18.0
  - jupyter
  - ipykernel
  - setuptools<70
  - pip
  - pip:
    - neighpy
