c
c ----------------------------------------------------------------------------
c
c	An example of a driver program that calls the 
c	Neighbourhood algorithm routines to search a 
c	parameter space. See HTML manual for more details.
c					
c                                               M. Sambridge, RSES, ANU.
c						Last updated Sept. 1999.
c
c ----------------------------------------------------------------------------

c					MEMORY AND ARRAY SIZES
c
c					The NA routines use the
c					following include file to define
c					all parameters controlling
c					memory required by the arrays.
c
c					A description of each parameter,
c					indicating which ones should be 
c					changed to fit your application
c					can be found in 'na_param.inc' 
c
c	include 	'na_param.inc'
c
c					INPUT AND OUTPUT
c       Input files:
c                   na.in       	Contains options for Neighbourhood 
c					algorithm (see HTML manual)
c
c       Output files:
c                   na.sum      	summary of results
c
c                   na.nad      	NAD (NA direct access file of models)
c
c                   sobol.coeff 	initializing data used for
c                               	quasi-random sequences
c					(This is output for reference only)
c
c       Comments:
c                The NAD file is a direct access compact format file
c                containing all models generated by the neighbourhood
c                algorithm. (NAD files can be read in by multi-dimensional
c                integration program NA-Bayes and plot program S-plot.)
c
c		 Logical units 30-40 are reserved for use by NA subroutines
c		 The user specific routines should not use these values
c		 for logical units.
c		 The NA routines also write to LU 6 as standard out.
c
c ----------------------------------------------------------------------------
c
c					Call NA routine to do the work		

      Program kine_na

      call na
        
      stop
      end
c-------------------------------------------------------------------------
c
c	user_init - performs all user specific initialization tasks. 
c		    In this case for receiver receiver function inversion.
c
c	Input: - none
c
c	Output:
c	      nd		:Number of dimensions in parameter space
c	      ranges(2,nd)	:bounds on parameter space
c	      scales(nd+1)	:scale factors in parameter space
c
c-------------------------------------------------------------------------

      subroutine user_init(nd,ranges,scales)
c						initialize receiver
c						function forward modelling
      include 'kine_subs/kine_param.inc'

      real*4		ranges(2,*),scales(*)
      real*4		observed_data(maxdata,maxwave),
     &                  predicted_data(maxdata,maxwave),
     &			weight(maxwave,3),
     &			constant_a(maxwave),
     &			constant_c(maxwave),
     &			time_shift(maxwave),
     &			time_begin(maxwave),
     &			time_end(maxwave)
      real*4		slip0(1600)
      real*4		estk,edip
      
      integer		ndd,nstk,ndip,nell,islip0,ishape
      integer		ndata, nwave, nsource
      
      logical		verbose,debug,timing,summary
      logical		lroot
      
      character*40	chars,kname,fname(maxwave)
c     Info and Logical unit common 
c     blocks used by NA routines
c     
      character   headfile*50,sourcefile*10,statfile*10,fileout*10,
     &     histfile*50, filename*50, axires*50
      
      common /NA_IO/lu_na,lu_out,lu_sum,lu_det,lu_sob,lu_dis,
     &     lu_nad,verbose,debug,timing,summary
      common /NAMPI/iproc,nproc,lroot
      common /rfi_com/observed_data, predicted_data, weight,
     &     constant_a, constant_c, time_shift,
     &     time_begin, time_end, ndata,
     &     nwave, fs, lu_mod, fname, nd
      common /ellipse/ndd,nstk,ndip,nell,islip0,estk,edip,slip0,ishape
      
c     
c     Set up logical units 
c     LUs for standard input and 
c     output
      
      lu_rfi = 15
      lu_out = 6
      lu_od = 28
c     
c     
c     Set up logical units for kine files
c     LU for input of velocity 
c     model
      lu_vel = 11
c						LU for output of model 
c						parameters
      lu_mod = 13
      
      open(66,file='misfits.dat',status='unknown')
      open(67,file='minmisfits.dat',status='unknown')
      open(68,file='models.dat',status='unknown')
      open(lu_rfi,file='kine_files/kine.in',status='old')
      
      read(lu_rfi,*)
      read(lu_rfi,*)
      read(lu_rfi,*) 
      
      if(lroot)write(lu_out,*)
      if(lroot)write(lu_out,*)' User routines output'  
      if(lroot)write(lu_out,*)
      if(lroot)write(lu_out,*)' Opening kine files...'
      
      read(lu_rfi,'(a)') chars
      lw=lofw(chars)
      write(kname,'("kine_files/",a,a1)') chars(1:lw),char(0)
      if(lroot)write(lu_out,*)
      if(lroot)write(lu_out,*) '* Now open ... ',kname(1:lw+19)
      open(lu_vel,file=kname,status='old')
      
      read(lu_rfi,'(a)') chars
      lw=lofw(chars)
      write(kname,'("kine_files/",a,a1)') chars(1:lw),char(0)
      if(lroot)write(lu_out,*)
      if(lroot)write(lu_out,*) '* Now open ... ',kname(1:lw+19)
      open(lu_mod, file=kname, status='unknown')
      
c     INFO SUR LES ELLIPSES
      
      read(lu_rfi,*) ndd
      read(lu_rfi,*) estk,edip,nstk,ndip
      read(lu_rfi,*) nell
      read(lu_rfi,*) nd
      read(lu_rfi,*) islip0
      read(lu_rfi,*) ishape
      write(*,*) ndd,estk,edip,nstk,ndip,nell,islip0,ishape
      if (islip0.eq.1) then
         open(69,file='slip0.dat',status='old')
         do i=1,ndd
            read(69,*)slip0(i)
         enddo
         close(69)
      else
         do i=1,ndd
            slip0(i)=0
         enddo
      endif	

c     
c     Read in velocity model 
c     and ranges of the parameters
      call read_vmodelNA(lu_vel, ranges, scales, nd) 
      close(lu_vel)

      nsource=nd
c     
c     Read in ORFs in SAC format
      read(lu_rfi,*) nwave
      
      
      do iw=1,3
         read(lu_rfi,'(a)') chars
         lw=lofw(chars)
         write(fname(iw),'("kine_files/REAL_DAT/",a,a1)') 
     &        chars(1:lw),char(0)
         if(lroot)write(lu_out,*)
         if(lroot)write(lu_out,*) '* Read in data from ',
     &        fname(iw)(1:lw+20)
         
         read(lu_rfi,*) time_begin(iw), time_end(iw), ndata
         if(lroot)write(lu_out,*) '* Time window =',time_begin(iw),
     &        ' - ',time_end(iw)
         if(lroot)write(lu_out,*)' '
         
         open(lu_od,file=fname(iw),status='old')
         do ii=1,ndata*nwave
            read(lu_od,*) observed_data(ii,iw)
         enddo
         close(lu_od)
         
      end do
      
      do iww=1,nwave
         read(lu_rfi,*)(weight(iww,iw),iw=1,3)
         write(*,*)(weight(iww,iw),iw=1,3)
      enddo
      close(lu_rfi)
c     
c     
      
      
      if(lroot)write(lu_out,*)
c     if(lroot)write(lu_out,101)
      
 100  format(1x,60("-")//)
 101  format(/1x,60("-")/)
      
      return
      end
c
c-------------------------------------------------------------------------
c
c	forward - performs forward modelling for user supplied problem.
c		  In this case it calculates predicted receiver function
c		  for a single model and calculates the misfit measure
c		  between observation and prediction.
c
c	Input: 
c	      nd		:Number of dimensions in parameter space
c	      model(nd)		:input velocity model
c
c	Output:
c	      lppd		:negative log(ppd)
c
c-------------------------------------------------------------------------

      subroutine forward(nd,model,lppd)
      
c     initialize receiver
c     function forward modelling
      include 'kine_subs/kine_param.inc'
      
      real*4		lppd
      real*4		misfitval
      real*4		model(nd)
      
      real*8		rmodel(max_nd)
      
      real*4		observed_data(maxdata,maxwave),
     &     predicted_data(maxdata,maxwave),
     &     weight(maxwave,3),
     &     constant_a(maxwave),
     &     constant_c(maxwave),
     &     time_shift(maxwave),
     &     time_begin(maxwave),
     &     time_end(maxwave)
      real*4		slip0(1600)
      real*4		estk,edip
      
      integer		ndd,nstk,ndip,nell,islip0,ishape
      
      integer		ndata, nd
      
      logical		verbose,debug,timing,summary
      
      character*40	fname(maxwave)
c     
c     Info and Logical unit common 
c     blocks used by NA routines
      
      common /NA_IO/lu_na,lu_out,lu_sum,lu_det,lu_sob,lu_dis,
     &                lu_nad,verbose,debug,timing,summary
      
      
      common /rfi_com/observed_data, predicted_data, weight,
     &     constant_a, constant_c, time_shift, 
     &     time_begin, time_end, ndata,
     &                  nwave, fs, lu_mod, fname
      
      common /ellipse/ndd,nstk,ndip,nell,islip0,estk,edip,slip0,ishape
c     
c     Set up logical units 
c				LU''s for standard input and 
c     output
      
      do j=1,nd
         rmodel(j) = dble(model(j))
         write(68,*)rmodel(j)
      end do
c     Perform forward modelling
c     on model `rmodel.
c     
      call forward_modelling(rmodel,nd,ndata,nwave, 
     &     predicted_data)
c     
c                                          Calculate misfit function
c     
      call calcmisfit(
     &     predicted_data, observed_data, ndata,
     &     nwave, misfitval,weight)
      
      
      lppd = misfitval
      write(66,*)misfitval
      
      call flush(66)
      return
      end
c     
c     *-------------------------------------------------------------------------
c     
c*	writemodels - user supplied routine to write out models produced
c*		      by Neighbourhood algorithm in user own format.
c
c*	Input: 
c	      nd		  :number of dimensions in parameter space
c	      ntot		  :number of models generated by NA 
c	      models(nd,ntot)     :models generated by NA
c	      misfit 		  :array of model misfits (-lppd)
c	      ns1  		  :initial sample size used by NA
c	      ns2  		  :normal sample size used by NA
c	      itmax  		  :number of iterations
c	      nh_max  		  :maximum length of nad file header 
c
c	Output:         
c	      nh  		  :length of nad file header 
c	      header(nh)  	  :character string containing nad file header
c
c-------------------------------------------------------------------------

      subroutine writemodels
     &     (nd, ntot, models, misfit, ns1, ns2, itmax,
     &     nh_max, nh, header)
      
      include 'kine_subs/kine_param.inc'
      
c     NA variables and arrays
      real*4		models(nd,*)
      real*4		misfit(ntot)
      real*4		mfitmin
      real*4		mfitminc
      real*4		mfitmean
      
      character*(*)   header
      
      logical		verbose,debug,timing,summary
      
c     Receiver function variables
c     and arrays
      real*8		rmodel(max_nd)
      
      real*4		observed_data(maxdata,maxwave),
     &     predicted_data(maxdata,maxwave),
     &     weight(maxwave,3),
     &     constant_a(maxwave),
     &     constant_c(maxwave),
     &     time_shift(maxwave),
     &     time_begin(maxwave),
     &     time_end(maxwave)
      
      real*4		slip0(1600)
      real*4		estk,edip
      
      integer		ndd,nstk,ndip,nell,islip0,ishape
      integer		ndata
      
      character*40	chars, fname(maxwave), out_name(maxwave),toto
      
c     
c     Info and Logical unit common 
c     block used by NA routines
      
      common /NA_IO/lu_na,lu_out,lu_sum,lu_det,lu_sob,lu_dis,
     &     lu_nad,verbose,debug,timing,summary
      
      
c     Receiver function 
c     common block
      
      common /rfi_com/observed_data, predicted_data, weight,
     &     constant_a, constant_c, time_shift,
     &     time_begin, time_end, ndata,
     &     nwave, fs, lu_mod, fname
      
      common /ellipse/ndd,nstk,ndip,nell,islip0,estk,edip,slip0,ishape
      
      nsource= nd
      lu_rfi = 19
      
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
      
c     write out models
c     at each iteration
      mfitmin = misfit(1)
      ns = ns1
      np = 0
      mopt = 1
c     turn off writing to 
c     standard out by setting
c     lu to zero
      write(*,*) 'here we are in write models'
      lu_out2 = lu_out
      lu_out2 = 0
      write(lu_mod,*)ns1,' Number of samples in starting pool'
      write(lu_mod,*)ns2,' Number of new samples per iteration'
      write(lu_mod,*)itmax,' Number of iterations'
c     
c     loop over iterations
      do it=1,itmax+1
         mfitminc = misfit(np+1)
         mfitmean = 0.0
c     find minimum and 
c     mean misfit
         do i=1,ns
            jj = np + i
            if(misfit(jj).lt.mfitmin)then
               mfitmin = misfit(jj)
               mopt = jj
            end if
            mfitminc = min(mfitminc,misfit(jj))
            mfitmean = mfitmean + misfit(jj)
         end do
         mfitmean = mfitmean/ns
c     write out all models
c     from this iteration
c     to receiver function
c     output file.
         
         write(lu_mod,801) it-1, mfitmin, mfitmean, mfitminc
         do i=1,ns
            jj = np + i
            call display_model
     &           (lu_mod, i, models(1,jj), nsource, misfit(jj))
         end do
         np = np + ns
         ns = ns2
c     Write out summary of
c     optimum model to
c     receiver function file
c     and NA summary file.
c     
         
         call output_summary(
     &        lu_out2, lu_sum, it-1, models(1,mopt), nd,
     &        np, mfitmin, mfitmean, mfitminc, mopt, nsource)
      end do
c     Write out final model
      
      call display_final(
     &     lu_out, models(1,mopt), nsource, nd)
      
      call display_final(
     &     lu_sum, models(1,mopt), nsource, nd)
      
      call display_final(
     &     lu_mod, models(1,mopt), nsource, nd)
      
      do j=1,nd
         rmodel(j) = dble(models(j,mopt))
      end do
      
c     repeat forward modelling 
c     for optimum model
      call forward_modelling(
     &     rmodel, nd, ndata, nwave, predicted_data)
c     
c     write out predicted 
c     receiver function 
c     for optimum model
      
c     open(lu_rfi,file='kine_files/kine.in',status='old')
c     do iw=1,11
c     read(lu_rfi,*)
c     enddo
      
c     do iw=1,3
c     read(lu_rfi,'(a)') chars
c     lw=lofw(chars)
c     write(out_name(iw),'("kine_files/BEST_DAT/",a,a1)') 
c     &   		chars(1:lw),char(0)
c     write(*,*) 'file in write model ', out_name(iw)(1:lw+20)
c     open(14,file=out_name(iw)(1:lw+20),status='unknown')
c     do ii=1,ndata*nwave
c     write(14,*) predicted_data(ii,iw)
c     end do
c     read(lu_rfi,*)
c     close(14)
c     end do
c     close(lu_rfi)
      
 801  format( 'iteration:',i5,',  misfit: min=',f10.5,
     &     ', mean=',f10.5,', minc=',f10.5 )

      
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
      return
      end
      
