!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.4.6)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitparameter(f2pysetupfunc)
      use parameter, only : fs
      use parameter, only : fd
      use parameter, only : ai
      use parameter, only : pi
      use parameter, only : pi2
      use parameter, only : in1
      use parameter, only : in2
      use parameter, only : in3
      use parameter, only : out
      use parameter, only : out2
      use parameter, only : ikmin
      use parameter, only : explim
      use parameter, only : elim
      use parameter, only : nkmax
      use parameter, only : rerr
      use parameter, only : fref
      external f2pysetupfunc
      call f2pysetupfunc(fs,fd,ai,pi,pi2,in1,in2,in3,out,out2,ikmin,expl&
     &im,elim,nkmax,rerr,fref)
      end subroutine f2pyinitparameter


