/* File: convmPymodule.c
 * This file is auto-generated with f2py (version:2.4.6).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Jul  2 03:20:26 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *convmPy_error;
static PyObject *convmPy_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = convmPy_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = convmPy_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(moment_conv,MOMENT_CONV)(int*,int*,double*,double*,int*,double*,double*,double*,int*,int*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** moment_conv ********************************/
static char doc_f2py_rout_convmPy_moment_conv[] = "\
sx,sy,sz = moment_conv(id,ics,t0,t1,icc,sx,sy,sz,[overwrite_sx,overwrite_sy,overwrite_sz])\n\nWrapper for ``moment_conv``.\
\n\nParameters\n----------\n"
"id : input int\n"
"ics : input int\n"
"t0 : input float\n"
"t1 : input float\n"
"icc : input int\n"
"sx : input rank-2 array('d') with bounds (ntx,nsx)\n"
"sy : input rank-2 array('d') with bounds (n2y,n1y)\n"
"sz : input rank-2 array('d') with bounds (n2z,n1z)\n"
"\nOther Parameters\n----------------\n"
"overwrite_sx : input int, optional\n    Default: 1\n"
"overwrite_sy : input int, optional\n    Default: 1\n"
"overwrite_sz : input int, optional\n    Default: 1\n"
"\nReturns\n-------\n"
"sx : rank-2 array('d') with bounds (ntx,nsx)\n"
"sy : rank-2 array('d') with bounds (n2y,n1y)\n"
"sz : rank-2 array('d') with bounds (n2z,n1z)";
/* extern void F_FUNC_US(moment_conv,MOMENT_CONV)(int*,int*,double*,double*,int*,double*,double*,double*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_convmPy_moment_conv(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,int*,double*,double*,double*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int id = 0;
    PyObject *id_capi = Py_None;
    int ics = 0;
    PyObject *ics_capi = Py_None;
    double t0 = 0;
    PyObject *t0_capi = Py_None;
    double t1 = 0;
    PyObject *t1_capi = Py_None;
    int icc = 0;
    PyObject *icc_capi = Py_None;
    double *sx = NULL;
    npy_intp sx_Dims[2] = {-1, -1};
    const int sx_Rank = 2;
    PyArrayObject *capi_sx_as_array = NULL;
    int capi_sx_intent = 0;
    int capi_overwrite_sx = 1;
    PyObject *sx_capi = Py_None;
    double *sy = NULL;
    npy_intp sy_Dims[2] = {-1, -1};
    const int sy_Rank = 2;
    PyArrayObject *capi_sy_as_array = NULL;
    int capi_sy_intent = 0;
    int capi_overwrite_sy = 1;
    PyObject *sy_capi = Py_None;
    double *sz = NULL;
    npy_intp sz_Dims[2] = {-1, -1};
    const int sz_Rank = 2;
    PyArrayObject *capi_sz_as_array = NULL;
    int capi_sz_intent = 0;
    int capi_overwrite_sz = 1;
    PyObject *sz_capi = Py_None;
    int nsx = 0;
    int ntx = 0;
    int n1y = 0;
    int n2y = 0;
    int n1z = 0;
    int n2z = 0;
    static char *capi_kwlist[] = {"id","ics","t0","t1","icc","sx","sy","sz","overwrite_sx","overwrite_sy","overwrite_sz",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|iii:convmPy.moment_conv",\
        capi_kwlist,&id_capi,&ics_capi,&t0_capi,&t1_capi,&icc_capi,&sx_capi,&sy_capi,&sz_capi,&capi_overwrite_sx,&capi_overwrite_sy,&capi_overwrite_sz))
        return NULL;
/*frompyobj*/
    /* Processing variable ics */
        f2py_success = int_from_pyobj(&ics,ics_capi,"convmPy.moment_conv() 2nd argument (ics) can't be converted to int");
    if (f2py_success) {
    /* Processing variable t0 */
        f2py_success = double_from_pyobj(&t0,t0_capi,"convmPy.moment_conv() 3rd argument (t0) can't be converted to double");
    if (f2py_success) {
    /* Processing variable t1 */
        f2py_success = double_from_pyobj(&t1,t1_capi,"convmPy.moment_conv() 4th argument (t1) can't be converted to double");
    if (f2py_success) {
    /* Processing variable icc */
        f2py_success = int_from_pyobj(&icc,icc_capi,"convmPy.moment_conv() 5th argument (icc) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sx */
    capi_sx_intent |= (capi_overwrite_sx?0:F2PY_INTENT_COPY);
    ;
    capi_sx_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT|F2PY_INTENT_C;
    const char capi_errmess[] = "convmPy.convmPy.moment_conv: failed to create array from the 6th argument `sx`";
    capi_sx_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,sx_Dims,sx_Rank,  capi_sx_intent,sx_capi,capi_errmess);
    if (capi_sx_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = convmPy_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sx = (double *)(PyArray_DATA(capi_sx_as_array));

    /* Processing variable sy */
    capi_sy_intent |= (capi_overwrite_sy?0:F2PY_INTENT_COPY);
    ;
    capi_sy_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT|F2PY_INTENT_C;
    const char capi_errmess[] = "convmPy.convmPy.moment_conv: failed to create array from the 7th argument `sy`";
    capi_sy_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,sy_Dims,sy_Rank,  capi_sy_intent,sy_capi,capi_errmess);
    if (capi_sy_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = convmPy_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sy = (double *)(PyArray_DATA(capi_sy_as_array));

    /* Processing variable sz */
    capi_sz_intent |= (capi_overwrite_sz?0:F2PY_INTENT_COPY);
    ;
    capi_sz_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT|F2PY_INTENT_C;
    const char capi_errmess[] = "convmPy.convmPy.moment_conv: failed to create array from the 8th argument `sz`";
    capi_sz_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,sz_Dims,sz_Rank,  capi_sz_intent,sz_capi,capi_errmess);
    if (capi_sz_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = convmPy_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sz = (double *)(PyArray_DATA(capi_sz_as_array));

    /* Processing variable id */
        f2py_success = int_from_pyobj(&id,id_capi,"convmPy.moment_conv() 1st argument (id) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nsx */
    nsx = shape(sx,0);
    /* Processing variable ntx */
    ntx = shape(sx,1);
    /* Processing variable n1y */
    n1y = shape(sy,0);
    /* Processing variable n2y */
    n2y = shape(sy,1);
    /* Processing variable n1z */
    n1z = shape(sz,0);
    /* Processing variable n2z */
    n2z = shape(sz,1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&id,&ics,&t0,&t1,&icc,sx,sy,sz,&nsx,&ntx,&n1y,&n2y,&n1z,&n2z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNN",capi_sx_as_array,capi_sy_as_array,capi_sz_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable n2z */
    /* End of cleaning variable n1z */
    /* End of cleaning variable n2y */
    /* End of cleaning variable n1y */
    /* End of cleaning variable ntx */
    /* End of cleaning variable nsx */
    } /*if (f2py_success) of id*/
    /* End of cleaning variable id */
    }  /* if (capi_sz_as_array == NULL) ... else of sz */
    /* End of cleaning variable sz */
    }  /* if (capi_sy_as_array == NULL) ... else of sy */
    /* End of cleaning variable sy */
    }  /* if (capi_sx_as_array == NULL) ... else of sx */
    /* End of cleaning variable sx */
    } /*if (f2py_success) of icc*/
    /* End of cleaning variable icc */
    } /*if (f2py_success) of t1*/
    /* End of cleaning variable t1 */
    } /*if (f2py_success) of t0*/
    /* End of cleaning variable t0 */
    } /*if (f2py_success) of ics*/
    /* End of cleaning variable ics */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of moment_conv *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_parameter_def[] = {
  {"fs",0,{{-1}},NPY_INT, 1},
  {"fd",0,{{-1}},NPY_INT, 1},
  {"ai",0,{{-1}},NPY_CDOUBLE, 1},
  {"pi",0,{{-1}},NPY_DOUBLE, 1},
  {"pi2",0,{{-1}},NPY_DOUBLE, 1},
  {"in1",0,{{-1}},NPY_INT, 1},
  {"in2",0,{{-1}},NPY_INT, 1},
  {"in3",0,{{-1}},NPY_INT, 1},
  {"out",0,{{-1}},NPY_INT, 1},
  {"out2",0,{{-1}},NPY_INT, 1},
  {"ikmin",0,{{-1}},NPY_INT, 1},
  {"explim",0,{{-1}},NPY_DOUBLE, 1},
  {"elim",0,{{-1}},NPY_DOUBLE, 1},
  {"nkmax",0,{{-1}},NPY_INT, 1},
  {"rerr",0,{{-1}},NPY_DOUBLE, 1},
  {"fref",0,{{-1}},NPY_DOUBLE, 1},
  {NULL}
};

static void f2py_setup_parameter(char *fs,char *fd,char *ai,char *pi,char *pi2,char *in1,char *in2,char *in3,char *out,char *out2,char *ikmin,char *explim,char *elim,char *nkmax,char *rerr,char *fref) {
  int i_f2py=0;
  f2py_parameter_def[i_f2py++].data = fs;
  f2py_parameter_def[i_f2py++].data = fd;
  f2py_parameter_def[i_f2py++].data = ai;
  f2py_parameter_def[i_f2py++].data = pi;
  f2py_parameter_def[i_f2py++].data = pi2;
  f2py_parameter_def[i_f2py++].data = in1;
  f2py_parameter_def[i_f2py++].data = in2;
  f2py_parameter_def[i_f2py++].data = in3;
  f2py_parameter_def[i_f2py++].data = out;
  f2py_parameter_def[i_f2py++].data = out2;
  f2py_parameter_def[i_f2py++].data = ikmin;
  f2py_parameter_def[i_f2py++].data = explim;
  f2py_parameter_def[i_f2py++].data = elim;
  f2py_parameter_def[i_f2py++].data = nkmax;
  f2py_parameter_def[i_f2py++].data = rerr;
  f2py_parameter_def[i_f2py++].data = fref;
}
extern void F_FUNC(f2pyinitparameter,F2PYINITPARAMETER)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_parameter(void) {
  F_FUNC(f2pyinitparameter,F2PYINITPARAMETER)(f2py_setup_parameter);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"moment_conv",-1,{{-1}},0,0,(char *)  F_FUNC_US(moment_conv,MOMENT_CONV),  (f2py_init_func)f2py_rout_convmPy_moment_conv,doc_f2py_rout_convmPy_moment_conv},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "convmPy",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_convmPy(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = convmPy_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module convmPy (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.4.6");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'convmPy' is auto-generated with f2py (version:2.4.6).\nFunctions:\n"
"    sx,sy,sz = moment_conv(id,ics,t0,t1,icc,sx,sy,sz,overwrite_sx=1,overwrite_sy=1,overwrite_sz=1)\n"
"Fortran 90/95 modules:\n""  parameter --- fs,fd,ai,pi,pi2,in1,in2,in3,out,out2,ikmin,explim,elim,nkmax,rerr,fref"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.4.6");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    convmPy_error = PyErr_NewException ("convmPy.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_convmPy_error", convmPy_error);
    Py_DECREF(convmPy_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "parameter", PyFortranObject_New(f2py_parameter_def,f2py_init_parameter));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"convmPy");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
